In [1]:
import numpy as np

# array数组

In [2]:
list = [1,2,3,4,5]
array = np.array(list)
array

array([1, 2, 3, 4, 5])

In [6]:
array.dtype

dtype('int32')

In [7]:
array.itemsize

4

In [8]:
array.shape

(5,)

In [9]:
array.size

5

In [10]:
array.fill(0)

In [11]:
array

array([0, 0, 0, 0, 0])

## 多维数组

In [20]:
list = ([ [1,2,3],
          [4,5,6],
          [7,8,9]])
array = np.array(list)

In [17]:
array[1] #打印第二行

array([4, 5, 6])

In [18]:
array[:,1] #打印第二列

array([2, 5, 8])

In [19]:
array[0, 0:2]

array([1, 2])

In [21]:
array2 = array #array2是array的引用

In [22]:
array2[1, 1] = 100
print(array2)
print(array)

[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]
[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]


In [23]:
#复制需要用copy()方法
array3 = array.copy()
print(array3)

[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]


## 数组元素索引

In [25]:
#可以按照bool类型索引元素
array = np.array([1,2,3,4,5,6,7,8])
mask = np.array([0,0,1,0,2,0,0,1], dtype = bool)
print(array[mask])

[3 5 8]


In [32]:
#随机数
random_array = np.random.rand(10)*100
print(random_array)

[87.15406932 18.65943243 26.17370782 74.22993095 72.80030468 17.82820298
 32.59354329  4.76372519  7.89250914 25.71430803]


In [33]:
mask = random_array > 50
mask

array([ True, False, False,  True,  True, False, False, False, False,
       False])

In [34]:
#定位到符合条件的元素位置
np.where(random_array > 30)

(array([0, 3, 4, 6], dtype=int64),)

In [35]:
#找到符合条件的元素的值
random_array[np.where(random_array > 30)]

array([87.15406932, 74.22993095, 72.80030468, 32.59354329])

## 数组类型

In [38]:
array = np.array([1,2,3,4,5], dtype=np.float32)
array

array([1., 2., 3., 4., 5.], dtype=float32)

In [39]:
#数组占用的字节数
array.nbytes

20

In [46]:
#存储任何元素的类型
array = np.array([1,2.5,"str"], dtype=object)
array

array([1, 2.5, 'str'], dtype=object)

In [47]:
#object类型的数组进行乘法运算
array *= 2
array

array([2, 5.0, 'strstr'], dtype=object)

## array数组的数值计算

In [50]:
array = np.array([[1,2,3], 
                  [4,5,6]])
#数组元素求和
print(np.sum(array))

21


指定要进行的操作是按照什么维度

In [51]:
np.sum(array, axis=0)

array([5, 7, 9])

In [52]:
array.ndim #维数

2

In [53]:
np.sum(array, axis=1)

array([ 6, 15])

In [54]:
np.sum(array, axis=-1)#沿着最后一个轴求和

array([ 6, 15])

直接调用nparray的方法也可以

In [55]:
array.sum(axis=0)

array([5, 7, 9])

In [57]:
array.prod() #乘积

720

In [58]:
array.prod(axis=0)

array([ 4, 10, 18])

In [59]:
array.min(axis=1)

array([1, 4])

In [60]:
array.max(0)

array([4, 5, 6])

In [62]:
array.argmin(axis=0) #找到最小值的索引

array([0, 0, 0], dtype=int64)

In [63]:
array.mean()#均值

3.5

In [64]:
array.std()#标准差

1.707825127659933

In [65]:
array.var()#方差

2.9166666666666665

In [66]:
#对最大最小值做限制
print(array)
array.clip(2,4)

[[1 2 3]
 [4 5 6]]


array([[2, 2, 3],
       [4, 4, 4]])

In [67]:
array.round()#四舍五入 decimals参数指定精度，精确到小数点第几位

array([[1, 2, 3],
       [4, 5, 6]])

排序

In [69]:
array=np.array([[1.5,1.3,7.5],
                [5.6,7.8,1.2]])
array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [71]:
np.sort(array) #默认按照最后一个轴排序

array([[1.3, 1.5, 7.5],
       [1.2, 5.6, 7.8]])

In [72]:
np.sort(array, axis=0)

array([[1.5, 1.3, 1.2],
       [5.6, 7.8, 7.5]])

In [74]:
np.argsort(array)#排序的索引值

array([[1, 0, 2],
       [2, 0, 1]], dtype=int64)

In [76]:
array = np.linspace(0,10,10) #0，10的范围内按照平均构造出来十个数
array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [79]:
values = np.array([2.5,6.5,9.5])
np.searchsorted(array, values)#打印插入的位置(必须是排序好的数组)

array([3, 6, 9], dtype=int64)

In [80]:
array = np.array([[1,0,6],
                  [1,7,0],
                  [2,3,1],
                  [2,4,0]])
array

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

In [81]:
index = np.lexsort([-1*array[:,0], array[:,2]]) #第二列升序的前提下，第一列降序 ??(好像有点问题)
index

array([3, 1, 2, 0], dtype=int64)

In [84]:
array = array[index]
array

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

## 数组形状操作

In [86]:
#按顺序生成一个数组
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
array.shape

(10,)

In [91]:
#改变数组形状
#1.直接改变shape值
array.shape=2,5

In [92]:
#2.调用reshape方法
array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [93]:
#注意：数组的大小不能改变

In [97]:
array = np.arange(10)
array = array[:, np.newaxis] #增加维度
array.shape

(10, 1)

In [99]:
array = array[:, np.newaxis, np.newaxis]
array.shape

(10, 1, 1, 1, 1, 1)

In [100]:
#压缩空的维度
array = array.squeeze()
array.shape

(10,)

In [103]:
#转置
array.shape=2,5
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [105]:
array = array.transpose() #需要将得到的矩阵赋给新矩阵
array

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

## 数组的连接

In [106]:
a = np.array([[123,456,789], [213,215,64]])
a

array([[123, 456, 789],
       [213, 215,  64]])

In [107]:
b = np.array([[2341,215,231], [78,85,875]])
b

array([[2341,  215,  231],
       [  78,   85,  875]])

c = np.concatenate((a,b)) #默认按第一个维度拼接
c

In [109]:
c = np.concatenate((a,b), axis=1)
c

array([[ 123,  456,  789, 2341,  215,  231],
       [ 213,  215,   64,   78,   85,  875]])

In [111]:
print(a.shape)
print(b.shape)
print(c.shape)

(2, 3)
(2, 3)
(2, 6)


In [113]:
c.flatten() #拉平,原始的数组不改变

array([ 123,  456,  789, 2341,  215,  231,  213,  215,   64,   78,   85,
        875])

In [114]:
c.flatten().shape

(12,)

## 数组生成

In [118]:
array = np.arange(2,20,2)
array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [119]:
np.arange(2,20,2, dtype=np.float32)  #不包含最后一个数字

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.], dtype=float32)

In [122]:
np.linspace(0,10,10)  #平均构造数字 ,包含最后一个数组

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [125]:
np.logspace(0,1,5)  #默认以10为底

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

### 构造网格

In [127]:
x = y = np.linspace(-5,5,5)
print(x,y)

[-5.  -2.5  0.   2.5  5. ] [-5.  -2.5  0.   2.5  5. ]


In [128]:
x,y = np.meshgrid(x,y)
x

array([[-5. , -2.5,  0. ,  2.5,  5. ],
       [-5. , -2.5,  0. ,  2.5,  5. ],
       [-5. , -2.5,  0. ,  2.5,  5. ],
       [-5. , -2.5,  0. ,  2.5,  5. ],
       [-5. , -2.5,  0. ,  2.5,  5. ]])

In [129]:
y

array([[-5. , -5. , -5. , -5. , -5. ],
       [-2.5, -2.5, -2.5, -2.5, -2.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 2.5,  2.5,  2.5,  2.5,  2.5],
       [ 5. ,  5. ,  5. ,  5. ,  5. ]])

In [130]:
#构造行向量
np.r_[0:10:1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
#构造列向量
np.c_[0:10:2]

array([[0],
       [2],
       [4],
       [6],
       [8]])

### 更常用的zero ones

In [133]:
np.zeros(3)

array([0., 0., 0.])

In [134]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [137]:
#构造全是n的矩阵
np.ones((5,5),dtype=np.float32) * 8

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]], dtype=float32)

In [142]:
#构造一个未初始化空矩阵
x = np.empty(5)
x

array([2.12199579e-314, 6.36598737e-314, 1.06099790e-313, 1.48539705e-313,
       1.90979621e-313])

In [143]:
x.fill(0)
x

array([0., 0., 0., 0., 0.])

In [144]:
#构造一个与参数大小相同的矩阵
array = np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [145]:
np.zeros_like(array)

array([0, 0, 0, 0])

In [146]:
np.ones_like(array)

array([1, 1, 1, 1])

## 运算

In [148]:
x = np.array([1,2])
y = np.array([3,4])
#对应位置相乘
np.multiply(x,y)

array([3, 8])

In [149]:
#点乘
np.dot(x,y)

11

In [150]:
x.shape = 2,1
y.shape = 1,2
np.dot(x,y)

array([[3, 4],
       [6, 8]])

In [157]:
#直接用乘号也是可以的
print(x*y)

[[3 4]
 [6 8]]


In [159]:
#判断元素是否相等
x == y

array([[False, False],
       [False, False]])

In [160]:
x

array([[1],
       [2]])

In [161]:
y

array([[3, 4]])

In [162]:
#可以对矩阵进行逻辑运算（与或）
x = np.array([1,1,1,4])
y = np.array([1,1,1,2])
print(x)
print(y)
x == y

[1 1 1 4]
[1 1 1 2]


array([ True,  True,  True, False])

In [163]:
np.logical_or(x,y)

array([ True,  True,  True,  True])

In [164]:
np.logical_and(x,y)

array([ True,  True,  True,  True])

In [165]:
np.logical_not(x,y)

array([0, 0, 0, 0])

## 随机模块

In [167]:
#所有值都在0-1之间
np.random.rand(3,2)

array([[0.50627319, 0.34569934],
       [0.3372569 , 0.39430219],
       [0.38911772, 0.61281489]])

In [170]:
#左闭右开的区间
np.random.randint(10, size=(5,4))

array([[1, 1, 0, 0],
       [2, 6, 8, 3],
       [3, 8, 3, 5],
       [9, 7, 9, 8],
       [7, 9, 8, 5]])

In [171]:
np.random.rand()

0.7103588813438374

In [174]:
#0-10之间随机选三个数
np.random.randint(0,10,3)

array([4, 2, 3])

In [177]:
#构造一个高斯分布
mu, sigma = 0, 0.1 #均值、方差
np.random.normal(mu, sigma, 10)

array([ 0.00793206, -0.1094142 , -0.01920881, -0.06306186, -0.13319817,
       -0.01939659, -0.09011584, -0.15824827,  0.08535872,  0.0340498 ])

In [180]:
#设置打印精度
np.set_printoptions(precision = 3)

In [181]:
np.random.normal(mu, sigma, 10)

array([ 0.188,  0.087, -0.113, -0.034,  0.067,  0.   , -0.067, -0.015,
        0.026, -0.171])

### 洗牌

In [184]:
array = np.arange(10)

In [185]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
np.random.shuffle(array)

In [187]:
array

array([4, 3, 5, 1, 8, 9, 0, 7, 2, 6])

#### 随机种子

In [ ]:
#应用场景：对比试验时每次按相同的方式打乱
np.random.seed(0)

## 文件操作

In [188]:
%%writefile test.txt
1 2 3 4 5 6
2 3 5 7 8 9

Writing test.txt


In [190]:
#python方法
data = []
with open('test.txt') as f:
    for line in f:
        fileds = line.split()
        cur_data = [float(x) for x in fileds]
        data.append(cur_data)
data = np.array(data)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 7., 8., 9.]])

In [191]:
#numpy方法 默认分隔符是空格、数据都是浮点型
data = np.loadtxt("test.txt")
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 7., 8., 9.]])

In [193]:
%%writefile test1.txt
1,2,3,4,5,6
2,3,5,7,8,9

Overwriting test1.txt


In [195]:
#指定分隔符
data = np.loadtxt("test1.txt", delimiter = ',')
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 7., 8., 9.]])

In [196]:
 %%writefile test2.txt
a,b,c,d,e,f
1,2,3,4,5,6
2,3,5,7,8,9

Writing test2.txt


In [198]:
data = np.loadtxt("test2.txt", delimiter = ',', skiprows=1)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 7., 8., 9.]])

In [199]:
#uescols=(0,1,4)使用某几列

In [200]:
array = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [203]:
np.savetxt('test3.txt', array, fmt="%d", delimiter=',')

## 读写array结构

In [204]:
array = np.array([1,2,3,4,5,6])

In [205]:
np.save('array.npy', array)

In [206]:
ary = np.load('array.npy')
ary

array([1, 2, 3, 4, 5, 6])

In [207]:
array1 = np.arange(0,10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [210]:
#打个压缩包，里面有a.npy和b.npy
np.savez('array1.npz', a=array, b=array1)

In [211]:
data = np.load('array1.npz')

In [216]:
data.keys()

KeysView(<numpy.lib.npyio.NpzFile object at 0x000001FEDA7EC5F8>)

In [213]:
data['a']

array([1, 2, 3, 4, 5, 6])

In [217]:
data['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])