In [1]:
#打印numpy版本
import numpy as np
print(np.__version__)

1.15.1


In [3]:
#构造一个全零的矩阵，并打印其占用内存的大小
z = np.zeros((5,5))
print('%d bytes' %(z.size *z.itemsize))

200 bytes


In [4]:
#打印一个函数的帮助文档，比如numpy.add
print(help(np.info(np.add)))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [8]:
#创建一个10-50的数组，并将其倒序排列
array = np.arange(10,50)
array = array[::-1]
array

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [15]:
#找到一个数组中不为0的索引
np.nonzero([1,2,0,56,0,0,2,0,1])

(array([0, 1, 3, 6, 8], dtype=int64),)

In [19]:
#随机构造一个3*3的矩阵，并打印其中的最大最小值
array = np.random.random((3,3))
print(array)
print(array.min())
print(array.max())

[[0.26157514 0.31709401 0.39435297]
 [0.59498079 0.76967747 0.95235   ]
 [0.21914601 0.77907649 0.57498712]]
0.21914600544730956
0.9523500025024697


In [23]:
#构造一个5*5矩阵，令其值都为1，并在最外圈加上一圈0
array = np.ones((5,5))
array = np.pad(array, pad_width=1, mode="constant", constant_values=0)
array

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [24]:
#构造一个shape为(6,7,8)的矩阵，并找到第100个元素的索引值
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [26]:
#对一个5*5的矩阵做归一化操作
array = np.random.random((5,5))
array_max = array.max()
array_min = array.min()
array = (array-array_min)/(array_max-array_min)
array

array([[0.71275083, 0.68747823, 0.        , 0.94192183, 0.55850793],
       [0.43287496, 0.56338247, 0.46362807, 1.        , 0.14268551],
       [0.37279974, 0.23114894, 0.33457434, 0.1772186 , 0.13209579],
       [0.18683649, 0.06124894, 0.28689579, 0.38224087, 0.19823537],
       [0.88176903, 0.60588264, 0.20865779, 0.51866297, 0.01311905]])

In [30]:
#找到两个数组中相同的值
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
print(z1)
print(z2)
print(np.intersect1d(z1, z2))

[8 8 5 4 9 7 6 1 3 3]
[3 3 6 0 1 0 2 1 1 2]
[1 3 6]


In [36]:
#得到昨天，今天，明天的日期
today = np.datetime64('today', "D")
yesterday = today - np.timedelta64(1, "D")
tomorrow = today + np.timedelta64(1, "D")
print(yesterday)
print(today)
print(tomorrow)

2022-01-13
2022-01-14
2022-01-15


In [39]:
#得到一个月中的所有天
np.arange('2022-01', '2022-02', dtype="datetime64[D]")

array(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
       '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
       '2022-01-09', '2022-01-10', '2022-01-11', '2022-01-12',
       '2022-01-13', '2022-01-14', '2022-01-15', '2022-01-16',
       '2022-01-17', '2022-01-18', '2022-01-19', '2022-01-20',
       '2022-01-21', '2022-01-22', '2022-01-23', '2022-01-24',
       '2022-01-25', '2022-01-26', '2022-01-27', '2022-01-28',
       '2022-01-29', '2022-01-30', '2022-01-31'], dtype='datetime64[D]')

In [41]:
#得到一个数的整数部分
z = np.random.uniform(0,10,10)
print(z)
print(np.floor(z))

[4.03285927 9.92979372 5.8502237  0.23474746 7.75863028 3.97829286
 4.08144085 6.09589923 0.24849256 0.2099996 ]
[4. 9. 5. 0. 7. 3. 4. 6. 0. 0.]


In [43]:
#构造一个数组，让它不能被改变
z = np.zeros(5)
z.flags.writeable = False

In [44]:
z[0] = 1

ValueError: assignment destination is read-only

In [45]:
#打印大数据的全部值、部分值
np.set_printoptions(threshold=5)
z = np.zeros((15,15))
z

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [47]:
np.set_printoptions(threshold=np.nan)
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [53]:
#找到在一个数组中，最接近一个数的索引
z = np.arange(100)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(z-v)) .argmin()
print(z[index])

42.59046376861958
43


In [57]:
#32位float类型和32位int类型转换
z = np.arange(10, dtype=np.float32)
print(z.dtype)
z = z.astype(np.int32)
print(z.dtype)

float32
int32


In [59]:
#打印数组元素位置与数值
z = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [94]:
#按照数组的某一列进行排序
z = np.random.randint(0,10, (3,3))
print(z)
print(z[z[:,1].argsort()])

[[1 4 5]
 [2 7 6]
 [6 0 8]]
[[6 0 8]
 [1 4 5]
 [2 7 6]]


In [96]:
#统计数组中每个数值出现的次数
z = np.array([1,1,1,2,2,3,3,4,5,8])
np.bincount(z)

array([0, 3, 2, 2, 1, 1, 0, 0, 1], dtype=int64)

In [99]:
#对一个四维数组最后两维求和
z = np.random.randint(0,10,(4,4,4,4))
res = z.sum(axis=(-2,-1))
res

array([[59, 68, 79, 69],
       [72, 74, 61, 66],
       [48, 68, 67, 72],
       [64, 52, 58, 59]])

In [103]:
#交换矩阵中的两行
z = np.arange(25).reshape(5,5)
print(z)
z[[0,1]] = z[[1,0]]
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [125]:
#找到一个数组中最常出现的数字
z = np.random.randint(0,10,50)
print(z)
print(z[np.bincount(z).argmax()])

[9 8 4 2 4 0 9 2 9 9 2 9 3 2 5 0 7 3 8 1 5 1 2 5 5 7 7 9 6 1 6 4 3 4 3 1 3
 9 2 3 9 4 5 9 9 3 0 9 7 2]
9


In [130]:
#快速查找TOP K
z = np.arange(10000)
np.random.shuffle(z)
n = 5
print(z[np.argpartition(-z, n)[:n]])

[9997 9996 9998 9999 9995]


In [136]:
#去掉一个数组中，所有元素都相同的数据
z = np.random.randint(0,3,(10,3))
z

array([[0, 2, 1],
       [1, 1, 1],
       [0, 0, 1],
       [1, 1, 0],
       [1, 1, 2],
       [0, 1, 0],
       [2, 0, 1],
       [1, 0, 2],
       [1, 1, 1],
       [1, 1, 0]])

In [137]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,5])
print(np.all(a == b)) #是否所有元素都一样
print(np.any(a == b))

False
True


In [138]:
e = np.all(z[:, 1:] == z[:, :-1], axis=1) 
print(e)

[False  True False False False False False False  True False]
